// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NS4.Models;

#nullable disable

namespace NS4.Data
{
    public partial class NS2Context : DbContext
    {
        //public NS2Context()
        //{
        //}

        public NS2Context(DbContextOptions<NS2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<VSales> VSales { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Part>(entity =>
            {
                entity.HasIndex(e => e.Code, "IX_Part_Code")
                    .IsUnique();

                entity.Property(e => e.Category).IsRequired();

                entity.Property(e => e.Code).IsRequired();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Uom)
                    .IsRequired()
                    .HasColumnName("UOM");
            });

            modelBuilder.Entity<Sales>(entity =>
            {
                entity.HasIndex(e => new { e.SalesNum, e.PartNum }, "Unique_SalesNum_PartNum")
                    .IsUnique()
                    .HasFilter("([SalesNum] IS NOT NULL AND [PartNum] IS NOT NULL)");

                entity.Property(e => e.FromWh).HasColumnName("FromWH");

                entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<VSales>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("V_Sales");

                entity.Property(e => e.FromWh).HasColumnName("FromWH");

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.PartNum).HasMaxLength(450);

                entity.Property(e => e.SalesNum).HasMaxLength(450);

                entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Uom)
                    .IsRequired()
                    .HasColumnName("UOM");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}