// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace NS3.Models
{
    public partial class Part
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Spec { get; set; }
        public string Uom { get; set; }
        public decimal UnitPrice { get; set; }
        public string SupplierCode { get; set; }
        public string Category { get; set; }
        public string Remarks { get; set; }
    }
}