// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace NS3.Models
{
    public partial class VSales
    {
        public int Id { get; set; }
        public string SalesNum { get; set; }
        public DateTime SalesDate { get; set; }
        public string PartNum { get; set; }
        public int Qty { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal SubTotal { get; set; }
        public string Currency { get; set; }
        public string CustomerCode { get; set; }
        public string FromWh { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Spec { get; set; }
        public string Uom { get; set; }
    }
}