// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ConsoleAppReadExcel.Models;

#nullable disable

namespace ConsoleAppReadExcel.Data
{
    public partial class NsdatabaseContext : DbContext
    {
        public NsdatabaseContext()
        {
        }

        public NsdatabaseContext(DbContextOptions<NsdatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Part> Part { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                //optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=NSDatabase;Integrated Security=true;");
                string strConn = "Server=(localdb)\\mssqllocaldb;Database=aspnet-NS-0BCAF605-7FEE-4BBC-9719-A05948C89400;Trusted_Connection=True;MultipleActiveResultSets=true";


                optionsBuilder.UseSqlServer(strConn);


            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=NSDatabase;Integrated Security=true");

            modelBuilder.Entity<Part>(entity =>
            {
                entity.Property(e => e.Category).IsRequired();

                entity.Property(e => e.Code).IsRequired();
                
                entity.HasIndex(e => e.Code).IsUnique();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Uom)
                    .IsRequired()
                    .HasColumnName("UOM");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}